<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="0" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-13T23:36:03 IDT" name="Suite" finished-at="2024-06-13T23:36:24 IDT" duration-ms="21101">
    <groups>
    </groups>
    <test started-at="2024-06-13T23:36:03 IDT" name="Test" finished-at="2024-06-13T23:36:24 IDT" duration-ms="21101">
      <class name="tests.LoginTestFailedDDT">
        <test-method is-config="true" signature="setUp()[pri:0, instance:tests.LoginTestFailedDDT@1b32cd16]" started-at="2024-06-13T23:36:03 IDT" name="setUp" finished-at="2024-06-13T23:36:11 IDT" duration-ms="8349" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="tc02_Login_Failed(java.lang.String, java.lang.String)[pri:0, instance:tests.LoginTestFailedDDT@1b32cd16]" started-at="2024-06-13T23:36:11 IDT" name="tc02_Login_Failed" description="Data Driven Test - Case: incorrect credentials" data-provider="getDataFromExcel" finished-at="2024-06-13T23:36:11 IDT" duration-ms="0" status="SKIP">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/Lazy]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/Lazy
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:49)
at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:145)
at org.testng.internal.Parameters.handleParameters(Parameters.java:797)
at org.testng.internal.Parameters.handleParameters(Parameters.java:740)
at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:59)
at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:38)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:789)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:308)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:71)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:113)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.lang.NoClassDefFoundError: org/apache/logging/log4j/util/Lazy
at org.apache.logging.log4j.core.selector.ClassLoaderContextSelector.<init>(ClassLoaderContextSelector.java:55)
at org.apache.logging.log4j.core.impl.Log4jContextFactory.createContextSelector(Log4jContextFactory.java:108)
at org.apache.logging.log4j.core.impl.Log4jContextFactory.<init>(Log4jContextFactory.java:60)
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:132)
at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:259)
at java.base/java.lang.Class.newInstance(Class.java:755)
at org.apache.logging.log4j.LogManager.<clinit>(LogManager.java:95)
at org.apache.poi.ooxml.POIXMLDocumentPart.<clinit>(POIXMLDocumentPart.java:56)
at utils.Excel.getTableArray(Excel.java:27)
at tests.LoginTestFailedDDT.getDataFromExcel(LoginTestFailedDDT.java:33)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:76)
at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
... 29 more
Caused by: java.lang.ClassNotFoundException: org.apache.logging.log4j.util.Lazy
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
... 46 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc02_Login_Failed -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.LoginTestFailedDDT@1b32cd16]" started-at="2024-06-13T23:36:12 IDT" name="tearDown" finished-at="2024-06-13T23:36:12 IDT" duration-ms="584" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.LoginTestFailedDDT -->
      <class name="tests.BuyProductE2ETest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:tests.BuyProductE2ETest@4bdcaf36]" started-at="2024-06-13T23:36:12 IDT" name="setUp" finished-at="2024-06-13T23:36:20 IDT" duration-ms="7191" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setupLogin()[pri:0, instance:tests.BuyProductE2ETest@4bdcaf36]" started-at="2024-06-13T23:36:20 IDT" name="setupLogin" description="Succsessful Login credentials" finished-at="2024-06-13T23:36:20 IDT" duration-ms="591" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setupLogin -->
        <test-method signature="tc01_BuyProduct()[pri:0, instance:tests.BuyProductE2ETest@4bdcaf36]" started-at="2024-06-13T23:36:20 IDT" name="tc01_BuyProduct" description="Buy Product E2E" finished-at="2024-06-13T23:36:23 IDT" duration-ms="3079" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc01_BuyProduct -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:tests.BuyProductE2ETest@4bdcaf36]" started-at="2024-06-13T23:36:23 IDT" name="tearDown" finished-at="2024-06-13T23:36:24 IDT" duration-ms="570" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- tests.BuyProductE2ETest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
